[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/yew-template-for-github-io/"
# public_url = "/{project_name}/"            # for {username}.github.io/{project_name}
# public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "css/",
    "static/",
]

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
    "-c",
    "[ ! -d \"./node_modules\" ] && npm i || :; npm run build_css",
]
